version: '3.8'

services:
  lumen:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
  nginx:
    build: ./docker/nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_SERVER_PORT}:80
    depends_on:
      - lumen

