name: staging deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.3.0'

      - name: Npm install
        run: npm i
        
      - name: Build
        run: |
          npm run build
          npm run export
          
      - name: SSH key generate
        run: echo "${SSH_PRIVATE_KEY}" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy
        run: rsync -crv -e "ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" dist/ ${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.PRODUCT_DEPLOY_PATH }}

